sudo: required
services:
    - docker

before_install:
  - docker build -t mrfredland/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mrfredland/react-test npm test -- --coverage

after_success:
  - docker build -t mrfredland/multi-client ./client
  - docker build -t mrfredland/multi-nginx ./nginx
  - docker build -t mrfredland/multi-server ./server
  - docker build -t mrfredland/multi-worker ./worker
  # Log in to the docker CLI
  # (Add environment to CI first)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  # Take image and push to dockerhub
  - docker push mrfredland/multi-client
  - docker push mrfredland/multi-nginx
  - docker push mrfredland/multi-server
  - docker push mrfredland/multi-worker
deploy:
  provider: eleasticbeanstalk
  region: eu-west-2
  app: multi-docker
  anv: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-497308702862
  bucket_path: docker-multi-ver2
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
